# Generated by Django 4.2.3 on 2023-08-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_delete_searchpictures_user_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphicupload',
            name='price',
        ),
        migrations.RemoveField(
            model_name='useraddpicture',
            name='price',
        ),
    ]
